// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum CaptureKindMessage { microphone, systemAudio }

enum CaptureOverflowPolicyMessage { dropOldest, dropNewest, failCapture }

enum AudioSessionPhaseMessage {
  prepared,
  starting,
  running,
  interrupted,
  stopping,
  stopped,
  failed,
}

/// Why the source timeline broke immediately before a frame.
enum DiscontinuityReasonMessage {
  droppedFrames,
  sourceRestart,
  clockReset,
  formatChange,
  unknown,
}

/// Mirrors `AVAuthorizationStatus` for the audio capture device.
enum MicrophonePermissionStatusMessage {
  notDetermined,
  granted,
  denied,
  restricted,
}

class PcmFormatMessage {
  PcmFormatMessage({required this.sampleRate, required this.channelCount});

  int sampleRate;

  int channelCount;

  List<Object?> _toList() {
    return <Object?>[sampleRate, channelCount];
  }

  Object encode() {
    return _toList();
  }

  static PcmFormatMessage decode(Object result) {
    result as List<Object?>;
    return PcmFormatMessage(
      sampleRate: result[0]! as int,
      channelCount: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PcmFormatMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sampleRate, other.sampleRate) &&
        _deepEquals(channelCount, other.channelCount);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PcmFormatMessage(sampleRate: $sampleRate, channelCount: $channelCount)';
  }
}

class CaptureRequestMessage {
  CaptureRequestMessage({
    required this.kind,
    required this.outputFormat,
    required this.frameDurationMicros,
    required this.maxBufferedDurationMicros,
    required this.overflowPolicy,
    required this.processIds,
    this.inputDeviceId,
    this.rawRecordingPath,
  });

  CaptureKindMessage kind;

  PcmFormatMessage outputFormat;

  int frameDurationMicros;

  int maxBufferedDurationMicros;

  CaptureOverflowPolicyMessage overflowPolicy;

  List<int> processIds;

  String? inputDeviceId;

  String? rawRecordingPath;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      outputFormat,
      frameDurationMicros,
      maxBufferedDurationMicros,
      overflowPolicy,
      processIds,
      inputDeviceId,
      rawRecordingPath,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CaptureRequestMessage decode(Object result) {
    result as List<Object?>;
    return CaptureRequestMessage(
      kind: result[0]! as CaptureKindMessage,
      outputFormat: result[1]! as PcmFormatMessage,
      frameDurationMicros: result[2]! as int,
      maxBufferedDurationMicros: result[3]! as int,
      overflowPolicy: result[4]! as CaptureOverflowPolicyMessage,
      processIds: (result[5]! as List<Object?>).cast<int>(),
      inputDeviceId: result[6] as String?,
      rawRecordingPath: result[7] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CaptureRequestMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) &&
        _deepEquals(outputFormat, other.outputFormat) &&
        _deepEquals(frameDurationMicros, other.frameDurationMicros) &&
        _deepEquals(
          maxBufferedDurationMicros,
          other.maxBufferedDurationMicros,
        ) &&
        _deepEquals(overflowPolicy, other.overflowPolicy) &&
        _deepEquals(processIds, other.processIds) &&
        _deepEquals(inputDeviceId, other.inputDeviceId) &&
        _deepEquals(rawRecordingPath, other.rawRecordingPath);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CaptureRequestMessage(kind: $kind, outputFormat: $outputFormat, frameDurationMicros: $frameDurationMicros, maxBufferedDurationMicros: $maxBufferedDurationMicros, overflowPolicy: $overflowPolicy, processIds: $processIds, inputDeviceId: $inputDeviceId, rawRecordingPath: $rawRecordingPath)';
  }
}

class CaptureSessionInfoMessage {
  CaptureSessionInfoMessage({
    required this.sessionId,
    required this.sourceId,
    required this.trackId,
    required this.clockId,
    required this.format,
  });

  int sessionId;

  String sourceId;

  String trackId;

  String clockId;

  PcmFormatMessage format;

  List<Object?> _toList() {
    return <Object?>[sessionId, sourceId, trackId, clockId, format];
  }

  Object encode() {
    return _toList();
  }

  static CaptureSessionInfoMessage decode(Object result) {
    result as List<Object?>;
    return CaptureSessionInfoMessage(
      sessionId: result[0]! as int,
      sourceId: result[1]! as String,
      trackId: result[2]! as String,
      clockId: result[3]! as String,
      format: result[4]! as PcmFormatMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CaptureSessionInfoMessage ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) &&
        _deepEquals(sourceId, other.sourceId) &&
        _deepEquals(trackId, other.trackId) &&
        _deepEquals(clockId, other.clockId) &&
        _deepEquals(format, other.format);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CaptureSessionInfoMessage(sessionId: $sessionId, sourceId: $sourceId, trackId: $trackId, clockId: $clockId, format: $format)';
  }
}

class AudioFrameMessage {
  AudioFrameMessage({
    required this.sessionId,
    required this.sequence,
    required this.sampleOffset,
    required this.timestampMicros,
    required this.float32Samples,
    required this.droppedFramesBefore,
    this.discontinuityReason,
  });

  int sessionId;

  int sequence;

  int sampleOffset;

  int timestampMicros;

  Uint8List float32Samples;

  int droppedFramesBefore;

  /// Null when the frame continues the previous one. Set for every reported
  /// gap, including the ones a rebuilt capture chain opens with no frame loss.
  DiscontinuityReasonMessage? discontinuityReason;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      sequence,
      sampleOffset,
      timestampMicros,
      float32Samples,
      droppedFramesBefore,
      discontinuityReason,
    ];
  }

  Object encode() {
    return _toList();
  }

  static AudioFrameMessage decode(Object result) {
    result as List<Object?>;
    return AudioFrameMessage(
      sessionId: result[0]! as int,
      sequence: result[1]! as int,
      sampleOffset: result[2]! as int,
      timestampMicros: result[3]! as int,
      float32Samples: result[4]! as Uint8List,
      droppedFramesBefore: result[5]! as int,
      discontinuityReason: result[6] as DiscontinuityReasonMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AudioFrameMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) &&
        _deepEquals(sequence, other.sequence) &&
        _deepEquals(sampleOffset, other.sampleOffset) &&
        _deepEquals(timestampMicros, other.timestampMicros) &&
        _deepEquals(float32Samples, other.float32Samples) &&
        _deepEquals(droppedFramesBefore, other.droppedFramesBefore) &&
        _deepEquals(discontinuityReason, other.discontinuityReason);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AudioFrameMessage(sessionId: $sessionId, sequence: $sequence, sampleOffset: $sampleOffset, timestampMicros: $timestampMicros, float32Samples: $float32Samples, droppedFramesBefore: $droppedFramesBefore, discontinuityReason: $discontinuityReason)';
  }
}

class AudioFrameBatchMessage {
  AudioFrameBatchMessage({required this.frames, required this.endOfStream});

  List<AudioFrameMessage> frames;

  bool endOfStream;

  List<Object?> _toList() {
    return <Object?>[frames, endOfStream];
  }

  Object encode() {
    return _toList();
  }

  static AudioFrameBatchMessage decode(Object result) {
    result as List<Object?>;
    return AudioFrameBatchMessage(
      frames: (result[0]! as List<Object?>).cast<AudioFrameMessage>(),
      endOfStream: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AudioFrameBatchMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(frames, other.frames) &&
        _deepEquals(endOfStream, other.endOfStream);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AudioFrameBatchMessage(frames: $frames, endOfStream: $endOfStream)';
  }
}

class AudioSessionEventMessage {
  AudioSessionEventMessage({
    required this.sessionId,
    required this.phase,
    this.code,
    this.message,
    this.receivingAudio,
    this.callbackCount,
    this.peakAmplitude,
    this.rms,
    this.nonZeroFramePercent,
    this.renderCycles,
    this.firstAudioAtMillis,
  });

  int sessionId;

  AudioSessionPhaseMessage phase;

  String? code;

  String? message;

  bool? receivingAudio;

  int? callbackCount;

  /// Largest absolute sample seen since the session started, 0...1 nominal.
  double? peakAmplitude;

  /// Root mean square over every converted sample since the session started.
  double? rms;

  /// Percentage of converted callback buffers that carried non-zero audio.
  double? nonZeroFramePercent;

  /// Hardware render callbacks delivered, including buffers a bounded queue
  /// dropped before conversion.
  int? renderCycles;

  /// Milliseconds from session creation to the first non-zero buffer.
  int? firstAudioAtMillis;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      phase,
      code,
      message,
      receivingAudio,
      callbackCount,
      peakAmplitude,
      rms,
      nonZeroFramePercent,
      renderCycles,
      firstAudioAtMillis,
    ];
  }

  Object encode() {
    return _toList();
  }

  static AudioSessionEventMessage decode(Object result) {
    result as List<Object?>;
    return AudioSessionEventMessage(
      sessionId: result[0]! as int,
      phase: result[1]! as AudioSessionPhaseMessage,
      code: result[2] as String?,
      message: result[3] as String?,
      receivingAudio: result[4] as bool?,
      callbackCount: result[5] as int?,
      peakAmplitude: result[6] as double?,
      rms: result[7] as double?,
      nonZeroFramePercent: result[8] as double?,
      renderCycles: result[9] as int?,
      firstAudioAtMillis: result[10] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AudioSessionEventMessage ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) &&
        _deepEquals(phase, other.phase) &&
        _deepEquals(code, other.code) &&
        _deepEquals(message, other.message) &&
        _deepEquals(receivingAudio, other.receivingAudio) &&
        _deepEquals(callbackCount, other.callbackCount) &&
        _deepEquals(peakAmplitude, other.peakAmplitude) &&
        _deepEquals(rms, other.rms) &&
        _deepEquals(nonZeroFramePercent, other.nonZeroFramePercent) &&
        _deepEquals(renderCycles, other.renderCycles) &&
        _deepEquals(firstAudioAtMillis, other.firstAudioAtMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AudioSessionEventMessage(sessionId: $sessionId, phase: $phase, code: $code, message: $message, receivingAudio: $receivingAudio, callbackCount: $callbackCount, peakAmplitude: $peakAmplitude, rms: $rms, nonZeroFramePercent: $nonZeroFramePercent, renderCycles: $renderCycles, firstAudioAtMillis: $firstAudioAtMillis)';
  }
}

class AudioProcessMessage {
  AudioProcessMessage({
    required this.processId,
    required this.bundleId,
    required this.isProducingAudio,
  });

  int processId;

  String bundleId;

  bool isProducingAudio;

  List<Object?> _toList() {
    return <Object?>[processId, bundleId, isProducingAudio];
  }

  Object encode() {
    return _toList();
  }

  static AudioProcessMessage decode(Object result) {
    result as List<Object?>;
    return AudioProcessMessage(
      processId: result[0]! as int,
      bundleId: result[1]! as String,
      isProducingAudio: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AudioProcessMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(processId, other.processId) &&
        _deepEquals(bundleId, other.bundleId) &&
        _deepEquals(isProducingAudio, other.isProducingAudio);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AudioProcessMessage(processId: $processId, bundleId: $bundleId, isProducingAudio: $isProducingAudio)';
  }
}

class AudioInputDeviceMessage {
  AudioInputDeviceMessage({
    required this.id,
    required this.label,
    required this.isDefault,
  });

  String id;

  String label;

  bool isDefault;

  List<Object?> _toList() {
    return <Object?>[id, label, isDefault];
  }

  Object encode() {
    return _toList();
  }

  static AudioInputDeviceMessage decode(Object result) {
    result as List<Object?>;
    return AudioInputDeviceMessage(
      id: result[0]! as String,
      label: result[1]! as String,
      isDefault: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AudioInputDeviceMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(label, other.label) &&
        _deepEquals(isDefault, other.isDefault);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AudioInputDeviceMessage(id: $id, label: $label, isDefault: $isDefault)';
  }
}

class PlaybackRequestMessage {
  PlaybackRequestMessage({
    required this.inputFormat,
    required this.maxBufferedDurationMicros,
  });

  PcmFormatMessage inputFormat;

  int maxBufferedDurationMicros;

  List<Object?> _toList() {
    return <Object?>[inputFormat, maxBufferedDurationMicros];
  }

  Object encode() {
    return _toList();
  }

  static PlaybackRequestMessage decode(Object result) {
    result as List<Object?>;
    return PlaybackRequestMessage(
      inputFormat: result[0]! as PcmFormatMessage,
      maxBufferedDurationMicros: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlaybackRequestMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(inputFormat, other.inputFormat) &&
        _deepEquals(maxBufferedDurationMicros, other.maxBufferedDurationMicros);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlaybackRequestMessage(inputFormat: $inputFormat, maxBufferedDurationMicros: $maxBufferedDurationMicros)';
  }
}

class PlaybackSessionInfoMessage {
  PlaybackSessionInfoMessage({
    required this.sessionId,
    required this.clockId,
    required this.format,
  });

  int sessionId;

  String clockId;

  PcmFormatMessage format;

  List<Object?> _toList() {
    return <Object?>[sessionId, clockId, format];
  }

  Object encode() {
    return _toList();
  }

  static PlaybackSessionInfoMessage decode(Object result) {
    result as List<Object?>;
    return PlaybackSessionInfoMessage(
      sessionId: result[0]! as int,
      clockId: result[1]! as String,
      format: result[2]! as PcmFormatMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlaybackSessionInfoMessage ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) &&
        _deepEquals(clockId, other.clockId) &&
        _deepEquals(format, other.format);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlaybackSessionInfoMessage(sessionId: $sessionId, clockId: $clockId, format: $format)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is CaptureKindMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is CaptureOverflowPolicyMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is AudioSessionPhaseMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is DiscontinuityReasonMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is MicrophonePermissionStatusMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is PcmFormatMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is CaptureRequestMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is CaptureSessionInfoMessage) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is AudioFrameMessage) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is AudioFrameBatchMessage) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is AudioSessionEventMessage) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is AudioProcessMessage) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is AudioInputDeviceMessage) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is PlaybackRequestMessage) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is PlaybackSessionInfoMessage) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : CaptureKindMessage.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null
            ? null
            : CaptureOverflowPolicyMessage.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : AudioSessionPhaseMessage.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : DiscontinuityReasonMessage.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null
            ? null
            : MicrophonePermissionStatusMessage.values[value];
      case 134:
        return PcmFormatMessage.decode(readValue(buffer)!);
      case 135:
        return CaptureRequestMessage.decode(readValue(buffer)!);
      case 136:
        return CaptureSessionInfoMessage.decode(readValue(buffer)!);
      case 137:
        return AudioFrameMessage.decode(readValue(buffer)!);
      case 138:
        return AudioFrameBatchMessage.decode(readValue(buffer)!);
      case 139:
        return AudioSessionEventMessage.decode(readValue(buffer)!);
      case 140:
        return AudioProcessMessage.decode(readValue(buffer)!);
      case 141:
        return AudioInputDeviceMessage.decode(readValue(buffer)!);
      case 142:
        return PlaybackRequestMessage.decode(readValue(buffer)!);
      case 143:
        return PlaybackSessionInfoMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(
  _PigeonCodec(),
);

class DarwinAudioHostApi {
  /// Constructor for [DarwinAudioHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DarwinAudioHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<CaptureSessionInfoMessage> prepareCapture(
    CaptureRequestMessage request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.prepareCapture$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CaptureSessionInfoMessage;
  }

  Future<void> startCapture(int sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.startCapture$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<AudioFrameBatchMessage> readCaptureFrames(
    int sessionId,
    int maxFrames,
    int timeoutMillis,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.readCaptureFrames$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sessionId, maxFrames, timeoutMillis],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as AudioFrameBatchMessage;
  }

  Future<void> stopCapture(int sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.stopCapture$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> abortCapture(int sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.abortCapture$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> disposeCapture(int sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.disposeCapture$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<bool> isSystemAudioCaptureSupported() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.isSystemAudioCaptureSupported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> requestSystemAudioCapturePermission() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.requestSystemAudioCapturePermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<MicrophonePermissionStatusMessage> microphonePermissionStatus() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.microphonePermissionStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as MicrophonePermissionStatusMessage;
  }

  Future<MicrophonePermissionStatusMessage>
  requestMicrophonePermission() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.requestMicrophonePermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as MicrophonePermissionStatusMessage;
  }

  Future<int> cleanupOrphanedAggregateDevices() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.cleanupOrphanedAggregateDevices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<List<AudioInputDeviceMessage>> listAudioInputDevices() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.listAudioInputDevices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>)
        .cast<AudioInputDeviceMessage>();
  }

  Future<List<AudioProcessMessage>> listAudioProcesses() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.listAudioProcesses$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<AudioProcessMessage>();
  }

  Future<PlaybackSessionInfoMessage> preparePlayback(
    PlaybackRequestMessage request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.preparePlayback$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PlaybackSessionInfoMessage;
  }

  Future<void> startPlayback(int sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.startPlayback$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> writePlaybackFrames(
    int sessionId,
    List<AudioFrameMessage> frames,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.writePlaybackFrames$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sessionId, frames],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> finishPlayback(int sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.finishPlayback$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> abortPlayback(int sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.abortPlayback$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> disposePlayback(int sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.disposePlayback$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

/// Returns a broadcast [Stream] of events from the `sessionEvents` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<AudioSessionEventMessage> sessionEvents({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel sessionEventsChannel = EventChannel(
    'dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioEventChannelApi.sessionEvents$instanceName',
    pigeonMethodCodec,
  );
  return sessionEventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as AudioSessionEventMessage;
  });
}
