// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum CaptureKindMessage: Int, CaseIterable {
  case microphone = 0
  case systemAudio = 1
}

enum CaptureOverflowPolicyMessage: Int, CaseIterable {
  case dropOldest = 0
  case dropNewest = 1
  case failCapture = 2
}

enum AudioSessionPhaseMessage: Int, CaseIterable {
  case prepared = 0
  case starting = 1
  case running = 2
  case interrupted = 3
  case stopping = 4
  case stopped = 5
  case failed = 6
}

/// Generated class from Pigeon that represents data sent in messages.
struct PcmFormatMessage: Hashable, CustomStringConvertible {
  var sampleRate: Int64
  var channelCount: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PcmFormatMessage? {
    let sampleRate = pigeonVar_list[0] as! Int64
    let channelCount = pigeonVar_list[1] as! Int64

    return PcmFormatMessage(
      sampleRate: sampleRate,
      channelCount: channelCount
    )
  }
  func toList() -> [Any?] {
    return [
      sampleRate,
      channelCount,
    ]
  }
  static func == (lhs: PcmFormatMessage, rhs: PcmFormatMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sampleRate, rhs.sampleRate) && MessagesPigeonInternal.deepEquals(lhs.channelCount, rhs.channelCount)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PcmFormatMessage")
    MessagesPigeonInternal.deepHash(value: sampleRate, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: channelCount, hasher: &hasher)
  }

  public var description: String {
    return "PcmFormatMessage(sampleRate: \(String(describing: sampleRate)), channelCount: \(String(describing: channelCount)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CaptureRequestMessage: Hashable, CustomStringConvertible {
  var kind: CaptureKindMessage
  var outputFormat: PcmFormatMessage
  var frameDurationMicros: Int64
  var maxBufferedDurationMicros: Int64
  var overflowPolicy: CaptureOverflowPolicyMessage
  var processIds: [Int64]
  var inputDeviceId: String? = nil
  var rawRecordingPath: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CaptureRequestMessage? {
    let kind = pigeonVar_list[0] as! CaptureKindMessage
    let outputFormat = pigeonVar_list[1] as! PcmFormatMessage
    let frameDurationMicros = pigeonVar_list[2] as! Int64
    let maxBufferedDurationMicros = pigeonVar_list[3] as! Int64
    let overflowPolicy = pigeonVar_list[4] as! CaptureOverflowPolicyMessage
    let processIds = pigeonVar_list[5] as! [Int64]
    let inputDeviceId: String? = nilOrValue(pigeonVar_list[6])
    let rawRecordingPath: String? = nilOrValue(pigeonVar_list[7])

    return CaptureRequestMessage(
      kind: kind,
      outputFormat: outputFormat,
      frameDurationMicros: frameDurationMicros,
      maxBufferedDurationMicros: maxBufferedDurationMicros,
      overflowPolicy: overflowPolicy,
      processIds: processIds,
      inputDeviceId: inputDeviceId,
      rawRecordingPath: rawRecordingPath
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      outputFormat,
      frameDurationMicros,
      maxBufferedDurationMicros,
      overflowPolicy,
      processIds,
      inputDeviceId,
      rawRecordingPath,
    ]
  }
  static func == (lhs: CaptureRequestMessage, rhs: CaptureRequestMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.kind, rhs.kind) && MessagesPigeonInternal.deepEquals(lhs.outputFormat, rhs.outputFormat) && MessagesPigeonInternal.deepEquals(lhs.frameDurationMicros, rhs.frameDurationMicros) && MessagesPigeonInternal.deepEquals(lhs.maxBufferedDurationMicros, rhs.maxBufferedDurationMicros) && MessagesPigeonInternal.deepEquals(lhs.overflowPolicy, rhs.overflowPolicy) && MessagesPigeonInternal.deepEquals(lhs.processIds, rhs.processIds) && MessagesPigeonInternal.deepEquals(lhs.inputDeviceId, rhs.inputDeviceId) && MessagesPigeonInternal.deepEquals(lhs.rawRecordingPath, rhs.rawRecordingPath)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CaptureRequestMessage")
    MessagesPigeonInternal.deepHash(value: kind, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: outputFormat, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: frameDurationMicros, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maxBufferedDurationMicros, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: overflowPolicy, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: processIds, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: inputDeviceId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rawRecordingPath, hasher: &hasher)
  }

  public var description: String {
    return "CaptureRequestMessage(kind: \(String(describing: kind)), outputFormat: \(String(describing: outputFormat)), frameDurationMicros: \(String(describing: frameDurationMicros)), maxBufferedDurationMicros: \(String(describing: maxBufferedDurationMicros)), overflowPolicy: \(String(describing: overflowPolicy)), processIds: \(String(describing: processIds)), inputDeviceId: \(String(describing: inputDeviceId)), rawRecordingPath: \(String(describing: rawRecordingPath)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CaptureSessionInfoMessage: Hashable, CustomStringConvertible {
  var sessionId: Int64
  var sourceId: String
  var trackId: String
  var clockId: String
  var format: PcmFormatMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CaptureSessionInfoMessage? {
    let sessionId = pigeonVar_list[0] as! Int64
    let sourceId = pigeonVar_list[1] as! String
    let trackId = pigeonVar_list[2] as! String
    let clockId = pigeonVar_list[3] as! String
    let format = pigeonVar_list[4] as! PcmFormatMessage

    return CaptureSessionInfoMessage(
      sessionId: sessionId,
      sourceId: sourceId,
      trackId: trackId,
      clockId: clockId,
      format: format
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      sourceId,
      trackId,
      clockId,
      format,
    ]
  }
  static func == (lhs: CaptureSessionInfoMessage, rhs: CaptureSessionInfoMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && MessagesPigeonInternal.deepEquals(lhs.sourceId, rhs.sourceId) && MessagesPigeonInternal.deepEquals(lhs.trackId, rhs.trackId) && MessagesPigeonInternal.deepEquals(lhs.clockId, rhs.clockId) && MessagesPigeonInternal.deepEquals(lhs.format, rhs.format)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CaptureSessionInfoMessage")
    MessagesPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sourceId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: trackId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: clockId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: format, hasher: &hasher)
  }

  public var description: String {
    return "CaptureSessionInfoMessage(sessionId: \(String(describing: sessionId)), sourceId: \(String(describing: sourceId)), trackId: \(String(describing: trackId)), clockId: \(String(describing: clockId)), format: \(String(describing: format)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AudioFrameMessage: Hashable, CustomStringConvertible {
  var sessionId: Int64
  var sequence: Int64
  var sampleOffset: Int64
  var timestampMicros: Int64
  var float32Samples: FlutterStandardTypedData
  var droppedFramesBefore: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AudioFrameMessage? {
    let sessionId = pigeonVar_list[0] as! Int64
    let sequence = pigeonVar_list[1] as! Int64
    let sampleOffset = pigeonVar_list[2] as! Int64
    let timestampMicros = pigeonVar_list[3] as! Int64
    let float32Samples = pigeonVar_list[4] as! FlutterStandardTypedData
    let droppedFramesBefore = pigeonVar_list[5] as! Int64

    return AudioFrameMessage(
      sessionId: sessionId,
      sequence: sequence,
      sampleOffset: sampleOffset,
      timestampMicros: timestampMicros,
      float32Samples: float32Samples,
      droppedFramesBefore: droppedFramesBefore
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      sequence,
      sampleOffset,
      timestampMicros,
      float32Samples,
      droppedFramesBefore,
    ]
  }
  static func == (lhs: AudioFrameMessage, rhs: AudioFrameMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && MessagesPigeonInternal.deepEquals(lhs.sequence, rhs.sequence) && MessagesPigeonInternal.deepEquals(lhs.sampleOffset, rhs.sampleOffset) && MessagesPigeonInternal.deepEquals(lhs.timestampMicros, rhs.timestampMicros) && MessagesPigeonInternal.deepEquals(lhs.float32Samples, rhs.float32Samples) && MessagesPigeonInternal.deepEquals(lhs.droppedFramesBefore, rhs.droppedFramesBefore)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AudioFrameMessage")
    MessagesPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sequence, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sampleOffset, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: timestampMicros, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: float32Samples, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: droppedFramesBefore, hasher: &hasher)
  }

  public var description: String {
    return "AudioFrameMessage(sessionId: \(String(describing: sessionId)), sequence: \(String(describing: sequence)), sampleOffset: \(String(describing: sampleOffset)), timestampMicros: \(String(describing: timestampMicros)), float32Samples: \(String(describing: float32Samples)), droppedFramesBefore: \(String(describing: droppedFramesBefore)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AudioFrameBatchMessage: Hashable, CustomStringConvertible {
  var frames: [AudioFrameMessage]
  var endOfStream: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AudioFrameBatchMessage? {
    let frames = pigeonVar_list[0] as! [AudioFrameMessage]
    let endOfStream = pigeonVar_list[1] as! Bool

    return AudioFrameBatchMessage(
      frames: frames,
      endOfStream: endOfStream
    )
  }
  func toList() -> [Any?] {
    return [
      frames,
      endOfStream,
    ]
  }
  static func == (lhs: AudioFrameBatchMessage, rhs: AudioFrameBatchMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.frames, rhs.frames) && MessagesPigeonInternal.deepEquals(lhs.endOfStream, rhs.endOfStream)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AudioFrameBatchMessage")
    MessagesPigeonInternal.deepHash(value: frames, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: endOfStream, hasher: &hasher)
  }

  public var description: String {
    return "AudioFrameBatchMessage(frames: \(String(describing: frames)), endOfStream: \(String(describing: endOfStream)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AudioSessionEventMessage: Hashable, CustomStringConvertible {
  var sessionId: Int64
  var phase: AudioSessionPhaseMessage
  var code: String? = nil
  var message: String? = nil
  var receivingAudio: Bool? = nil
  var callbackCount: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AudioSessionEventMessage? {
    let sessionId = pigeonVar_list[0] as! Int64
    let phase = pigeonVar_list[1] as! AudioSessionPhaseMessage
    let code: String? = nilOrValue(pigeonVar_list[2])
    let message: String? = nilOrValue(pigeonVar_list[3])
    let receivingAudio: Bool? = nilOrValue(pigeonVar_list[4])
    let callbackCount: Int64? = nilOrValue(pigeonVar_list[5])

    return AudioSessionEventMessage(
      sessionId: sessionId,
      phase: phase,
      code: code,
      message: message,
      receivingAudio: receivingAudio,
      callbackCount: callbackCount
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      phase,
      code,
      message,
      receivingAudio,
      callbackCount,
    ]
  }
  static func == (lhs: AudioSessionEventMessage, rhs: AudioSessionEventMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && MessagesPigeonInternal.deepEquals(lhs.phase, rhs.phase) && MessagesPigeonInternal.deepEquals(lhs.code, rhs.code) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message) && MessagesPigeonInternal.deepEquals(lhs.receivingAudio, rhs.receivingAudio) && MessagesPigeonInternal.deepEquals(lhs.callbackCount, rhs.callbackCount)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AudioSessionEventMessage")
    MessagesPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: phase, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: code, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: receivingAudio, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: callbackCount, hasher: &hasher)
  }

  public var description: String {
    return "AudioSessionEventMessage(sessionId: \(String(describing: sessionId)), phase: \(String(describing: phase)), code: \(String(describing: code)), message: \(String(describing: message)), receivingAudio: \(String(describing: receivingAudio)), callbackCount: \(String(describing: callbackCount)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AudioProcessMessage: Hashable, CustomStringConvertible {
  var processId: Int64
  var bundleId: String
  var isProducingAudio: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AudioProcessMessage? {
    let processId = pigeonVar_list[0] as! Int64
    let bundleId = pigeonVar_list[1] as! String
    let isProducingAudio = pigeonVar_list[2] as! Bool

    return AudioProcessMessage(
      processId: processId,
      bundleId: bundleId,
      isProducingAudio: isProducingAudio
    )
  }
  func toList() -> [Any?] {
    return [
      processId,
      bundleId,
      isProducingAudio,
    ]
  }
  static func == (lhs: AudioProcessMessage, rhs: AudioProcessMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.processId, rhs.processId) && MessagesPigeonInternal.deepEquals(lhs.bundleId, rhs.bundleId) && MessagesPigeonInternal.deepEquals(lhs.isProducingAudio, rhs.isProducingAudio)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AudioProcessMessage")
    MessagesPigeonInternal.deepHash(value: processId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bundleId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isProducingAudio, hasher: &hasher)
  }

  public var description: String {
    return "AudioProcessMessage(processId: \(String(describing: processId)), bundleId: \(String(describing: bundleId)), isProducingAudio: \(String(describing: isProducingAudio)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AudioInputDeviceMessage: Hashable, CustomStringConvertible {
  var id: String
  var label: String
  var isDefault: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AudioInputDeviceMessage? {
    let id = pigeonVar_list[0] as! String
    let label = pigeonVar_list[1] as! String
    let isDefault = pigeonVar_list[2] as! Bool

    return AudioInputDeviceMessage(
      id: id,
      label: label,
      isDefault: isDefault
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      label,
      isDefault,
    ]
  }
  static func == (lhs: AudioInputDeviceMessage, rhs: AudioInputDeviceMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.id, rhs.id) && MessagesPigeonInternal.deepEquals(lhs.label, rhs.label) && MessagesPigeonInternal.deepEquals(lhs.isDefault, rhs.isDefault)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AudioInputDeviceMessage")
    MessagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: label, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isDefault, hasher: &hasher)
  }

  public var description: String {
    return "AudioInputDeviceMessage(id: \(String(describing: id)), label: \(String(describing: label)), isDefault: \(String(describing: isDefault)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlaybackRequestMessage: Hashable, CustomStringConvertible {
  var inputFormat: PcmFormatMessage
  var maxBufferedDurationMicros: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlaybackRequestMessage? {
    let inputFormat = pigeonVar_list[0] as! PcmFormatMessage
    let maxBufferedDurationMicros = pigeonVar_list[1] as! Int64

    return PlaybackRequestMessage(
      inputFormat: inputFormat,
      maxBufferedDurationMicros: maxBufferedDurationMicros
    )
  }
  func toList() -> [Any?] {
    return [
      inputFormat,
      maxBufferedDurationMicros,
    ]
  }
  static func == (lhs: PlaybackRequestMessage, rhs: PlaybackRequestMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.inputFormat, rhs.inputFormat) && MessagesPigeonInternal.deepEquals(lhs.maxBufferedDurationMicros, rhs.maxBufferedDurationMicros)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlaybackRequestMessage")
    MessagesPigeonInternal.deepHash(value: inputFormat, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maxBufferedDurationMicros, hasher: &hasher)
  }

  public var description: String {
    return "PlaybackRequestMessage(inputFormat: \(String(describing: inputFormat)), maxBufferedDurationMicros: \(String(describing: maxBufferedDurationMicros)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlaybackSessionInfoMessage: Hashable, CustomStringConvertible {
  var sessionId: Int64
  var clockId: String
  var format: PcmFormatMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlaybackSessionInfoMessage? {
    let sessionId = pigeonVar_list[0] as! Int64
    let clockId = pigeonVar_list[1] as! String
    let format = pigeonVar_list[2] as! PcmFormatMessage

    return PlaybackSessionInfoMessage(
      sessionId: sessionId,
      clockId: clockId,
      format: format
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      clockId,
      format,
    ]
  }
  static func == (lhs: PlaybackSessionInfoMessage, rhs: PlaybackSessionInfoMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && MessagesPigeonInternal.deepEquals(lhs.clockId, rhs.clockId) && MessagesPigeonInternal.deepEquals(lhs.format, rhs.format)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlaybackSessionInfoMessage")
    MessagesPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: clockId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: format, hasher: &hasher)
  }

  public var description: String {
    return "PlaybackSessionInfoMessage(sessionId: \(String(describing: sessionId)), clockId: \(String(describing: clockId)), format: \(String(describing: format)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CaptureKindMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CaptureOverflowPolicyMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AudioSessionPhaseMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return PcmFormatMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return CaptureRequestMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return CaptureSessionInfoMessage.fromList(self.readValue() as! [Any?])
    case 135:
      return AudioFrameMessage.fromList(self.readValue() as! [Any?])
    case 136:
      return AudioFrameBatchMessage.fromList(self.readValue() as! [Any?])
    case 137:
      return AudioSessionEventMessage.fromList(self.readValue() as! [Any?])
    case 138:
      return AudioProcessMessage.fromList(self.readValue() as! [Any?])
    case 139:
      return AudioInputDeviceMessage.fromList(self.readValue() as! [Any?])
    case 140:
      return PlaybackRequestMessage.fromList(self.readValue() as! [Any?])
    case 141:
      return PlaybackSessionInfoMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CaptureKindMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? CaptureOverflowPolicyMessage {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? AudioSessionPhaseMessage {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? PcmFormatMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? CaptureRequestMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? CaptureSessionInfoMessage {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? AudioFrameMessage {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? AudioFrameBatchMessage {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? AudioSessionEventMessage {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? AudioProcessMessage {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? AudioInputDeviceMessage {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? PlaybackRequestMessage {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? PlaybackSessionInfoMessage {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

var messagesPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: MessagesPigeonCodecReaderWriter());


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DarwinAudioHostApi {
  func prepareCapture(request: CaptureRequestMessage, completion: @escaping (Result<CaptureSessionInfoMessage, Error>) -> Void)
  func startCapture(sessionId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func readCaptureFrames(sessionId: Int64, maxFrames: Int64, timeoutMillis: Int64, completion: @escaping (Result<AudioFrameBatchMessage, Error>) -> Void)
  func stopCapture(sessionId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func abortCapture(sessionId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func disposeCapture(sessionId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func isSystemAudioCaptureSupported(completion: @escaping (Result<Bool, Error>) -> Void)
  func requestSystemAudioCapturePermission(completion: @escaping (Result<Bool, Error>) -> Void)
  func listAudioInputDevices(completion: @escaping (Result<[AudioInputDeviceMessage], Error>) -> Void)
  func listAudioProcesses(completion: @escaping (Result<[AudioProcessMessage], Error>) -> Void)
  func preparePlayback(request: PlaybackRequestMessage, completion: @escaping (Result<PlaybackSessionInfoMessage, Error>) -> Void)
  func startPlayback(sessionId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func writePlaybackFrames(sessionId: Int64, frames: [AudioFrameMessage], completion: @escaping (Result<Void, Error>) -> Void)
  func finishPlayback(sessionId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func abortPlayback(sessionId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func disposePlayback(sessionId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DarwinAudioHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `DarwinAudioHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DarwinAudioHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let prepareCaptureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.prepareCapture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      prepareCaptureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! CaptureRequestMessage
        api.prepareCapture(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      prepareCaptureChannel.setMessageHandler(nil)
    }
    let startCaptureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.startCapture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startCaptureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        api.startCapture(sessionId: sessionIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startCaptureChannel.setMessageHandler(nil)
    }
    let readCaptureFramesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.readCaptureFrames\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readCaptureFramesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let maxFramesArg = args[1] as! Int64
        let timeoutMillisArg = args[2] as! Int64
        api.readCaptureFrames(sessionId: sessionIdArg, maxFrames: maxFramesArg, timeoutMillis: timeoutMillisArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readCaptureFramesChannel.setMessageHandler(nil)
    }
    let stopCaptureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.stopCapture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopCaptureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        api.stopCapture(sessionId: sessionIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopCaptureChannel.setMessageHandler(nil)
    }
    let abortCaptureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.abortCapture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      abortCaptureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        api.abortCapture(sessionId: sessionIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      abortCaptureChannel.setMessageHandler(nil)
    }
    let disposeCaptureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.disposeCapture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeCaptureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        api.disposeCapture(sessionId: sessionIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeCaptureChannel.setMessageHandler(nil)
    }
    let isSystemAudioCaptureSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.isSystemAudioCaptureSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSystemAudioCaptureSupportedChannel.setMessageHandler { _, reply in
        api.isSystemAudioCaptureSupported { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isSystemAudioCaptureSupportedChannel.setMessageHandler(nil)
    }
    let requestSystemAudioCapturePermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.requestSystemAudioCapturePermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestSystemAudioCapturePermissionChannel.setMessageHandler { _, reply in
        api.requestSystemAudioCapturePermission { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestSystemAudioCapturePermissionChannel.setMessageHandler(nil)
    }
    let listAudioInputDevicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.listAudioInputDevices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listAudioInputDevicesChannel.setMessageHandler { _, reply in
        api.listAudioInputDevices { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      listAudioInputDevicesChannel.setMessageHandler(nil)
    }
    let listAudioProcessesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.listAudioProcesses\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listAudioProcessesChannel.setMessageHandler { _, reply in
        api.listAudioProcesses { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      listAudioProcessesChannel.setMessageHandler(nil)
    }
    let preparePlaybackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.preparePlayback\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      preparePlaybackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PlaybackRequestMessage
        api.preparePlayback(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      preparePlaybackChannel.setMessageHandler(nil)
    }
    let startPlaybackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.startPlayback\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startPlaybackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        api.startPlayback(sessionId: sessionIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startPlaybackChannel.setMessageHandler(nil)
    }
    let writePlaybackFramesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.writePlaybackFrames\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writePlaybackFramesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let framesArg = args[1] as! [AudioFrameMessage]
        api.writePlaybackFrames(sessionId: sessionIdArg, frames: framesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      writePlaybackFramesChannel.setMessageHandler(nil)
    }
    let finishPlaybackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.finishPlayback\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      finishPlaybackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        api.finishPlayback(sessionId: sessionIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      finishPlaybackChannel.setMessageHandler(nil)
    }
    let abortPlaybackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.abortPlayback\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      abortPlaybackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        api.abortPlayback(sessionId: sessionIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      abortPlaybackChannel.setMessageHandler(nil)
    }
    let disposePlaybackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioHostApi.disposePlayback\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposePlaybackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        api.disposePlayback(sessionId: sessionIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposePlaybackChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class SessionEventsStreamHandler: PigeonEventChannelWrapper<AudioSessionEventMessage> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: SessionEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.audio_flutter_darwin.DarwinAudioEventChannelApi.sessionEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<AudioSessionEventMessage>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
